version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "5053:53/tcp"
      - "5053:53/udp"
      - "5067:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "8080:80/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: 'supersecret123'
      DNSSEC: 'true'
      WEBTHEME: 'default-dark'
      IPv6: 'false'
      PIHOLE_DNS_: 'dnscrypt#8053'
      DNS_BOGUS_PRIV: 'true'
      DNS_FQDN_REQUIRED: 'true'
      DNSMASQ_LISTENING: 'all'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
  dnscrypt:
    container_name: dnscrypt-proxy
    image: klutchell/dnscrypt-proxy
    ports:
      - "8053:53/tcp"
      - "8053:53/udp"
    volumes:
      - './dnscrypt-proxy.toml:/config/dnscrypt-proxy.toml'
    restart: unless-stopped